### PR TITLE
fix maven build

### PR DESCRIPTION
**Pull request by moniwe**
fix maven / jenkins nightly build by updating the version number of org.eclipse.license.feature.group

### CODE REVIEW

**Comment by genie-texlipse** [comment]
Can one of the admins verify this patch?

**Comment by turesheim** [comment]
Hi moniwe, do you mind singing up for the [ECA](https://www.eclipse.org/legal/ECA.php)? That way I can get your patch merged in. And thanks for caring :)

**Comment by moniwe** [comment]
hi, yes i signed this ... i am committer in eclipse 4diac. but since i changed my employer and also the email address i have somehow problems with my eclipse account.

**Comment by turesheim** [comment]
> hi, yes i signed this ... i am committer in eclipse 4diac. but since i changed my employer and also the email address i have somehow problems with my eclipse account.
Yes, your email-address connected to the Eclipse account is probably not current, you may want to choose one not connected to your employer.  Please contact emo@eclipse-foundation.org to have this remedied. My apologies if this appears as too much red tape. We are just making sure that everything produced under the Eclipse Foundation umbrella stays friendly to all sorts of consumers. Let me know if I can help.

**Comment by chrisguindon** [comment]
The validation is now passing! 

For some reason, Monika email address had a space at the beginning and the validation tool was unable to find her documents.

**Comment by turesheim** [comment]
I'm glad you figured it out Chris! And once again Monika, thanks for the patch.

**Pull request merged**
