### PR TITLE
typo in preference page text fixed

### PR DESCRIPTION
**Pull request by bugybunny**
"Use build in spell checker"  to ""Use built in spell checker" "

### CODE REVIEW

**Comment by genie-texlipse** [comment]
Can one of the admins verify this patch?

**Comment by bugybunny** [comment]
I have btw submitted the ECA (because I contribute to CDT), just with a different email address if that even is needed (I just got a message that I did not have it signed). Do I need to sign it again with this email?

**Comment by turesheim** [comment]
Hi and thanks for the patch – I think you can keep your GitHub username, but it must be added to your Eclipse Foundation account settings. Also all commits must be signed off. See https://github.com/eclipse/texlipse/blob/master/CONTRIBUTING.md

**Comment by bugybunny** [comment]
Sorry, that’s too much effort for this small commit, especially since I don’t have a gpg key yet and almost no understanding of this. Tried it and couldn’t do it in 5 minutes. You can fix it real quick ;-)

**Pull request closed without merging**
